### ISSUE TITLE
Protocol-oriented expected

### ISSUE THREAD

**Issue by between40and2** [CosmicMind/Graph#89]
Great job. However, the interface with so many classes are a bit hard to understand the structure and relationship, for beginners.

Also from match-perspective, someone, like myself, expect a Swift framework that present Graph with its match abstraction, and focus on graph math operations and algorithms. Rather than, this seems to me more CoreData/storage focused.

Could you please consider this as new features for GraphKit? Thanks

**Comment by daniel-jonathan** [comment]
Hey :), glad you are exploring GraphKit. So GraphKit is a few things, and storage is one of them. The idea is that if you do not need to think of storage, you are able to focus on writing algorithms. So here is how GraphKit breaks down: 
1. Entity, Action, Bond are used with Graph to create intricate relationships that are otherwise challenging to model. 
2. Structures are available, including List, Queue, Stack, Deque, RedBlackTree, SortedSet, SortedMultiSet, SortedDictionary, SortedMultiDictionary. 
3. These structures are used to write algorithms, whether it be stored objects as in point (1), or other forms of data, such as: String, Int, etc... 
4. A Data-Driven API that allows you to watch changes in stored data, which can influence real-time algorithms. 
5. Currently, a basic probability extension, which will be growing. 

That said, these are the foundations that needed to be built. There are many future plans to extend this. 

If you describe to me what you are looking to do, or a certain type of algorithm you are looking for, I can either help you by writing the additions to the framework, or by showing you how to achieve what you are looking for with the current library.

**Comment by daniel-jonathan** [comment]
I am closing this issue, as I don't see a direct question. Please feel free to create an issue with a direct fix or addition you would like :) all the best!
